version: "3"

volumes:
  mysql-data:

services:

  nginx:
    image: nginx:1.17.8-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${EXPOSE_WEB}:80
    depends_on:
      - laravel

  laravel:
    image: mamemomonga/laravel:7.0
    volumes:
      - ./app:/app
      - ./confd.yaml:/confd.yaml:ro
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${EXPOSE_MYSQL}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
 
  mail:
    image: mailhog/mailhog
    ports:
      - ${EXPOSE_MAILHOG}:8025

